In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

In [2]:
processed_df = pd.read_csv('./../datasets/csi_bli/csi_bli/df_csi_bli_processed.csv')
train_test_df = pd.read_csv('./../datasets/csi_bli/csi_bli/csi_bli_train_test_split.csv')
train_test_df

,Name,VH,VL,Signal Normalised to -ve Control,Signal Normalised to -ve Control_binarized,VH-VL,Clusters,Clusters_remapping,Train,Test
0,CL-222760,QVQLQESGPGLVKPSETLSLTCTVSGGSISCGGCYWTWIRQHPGKG...,DIQMTQSPSTLSASVGDRVTITCRASQSISSWLAWYQQKPGKAPKL...,1.327083,1,QVQLQESGPGLVKPSETLSLTCTVSGGSISCGGCYWTWIRQHPGKG...,538,538,1,0
1,CL-222759,QVQLQESGPGLVKPSETLSLTCAVSGASISLYYWSWIRQPAGKGLE...,DIQMTQSPSSVSASVGDRVAITCRASQGISSWLAWYQQKPGKAPKL...,2.158333,1,QVQLQESGPGLVKPSETLSLTCAVSGASISLYYWSWIRQPAGKGLE...,486,486,1,0
2,CL-222758,LVQLQESGPGLVKPSETLSLTCTVSGGSISSYYWSWIRQPAGKGLE...,DIQMTQSPSTLSASVGDRVTITCRASQSISSWLAWYQQKPGKAPKL...,1.029167,1,LVQLQESGPGLVKPSETLSLTCTVSGGSISSYYWSWIRQPAGKGLE...,71,71,1,0
3,CL-222757,QVQLQESGPGLVKPSETLSLTCTVSGGSISTYYWSWIRQPAGKGLE...,DIQMTQSPSSVSASVGDRVTITCRASQGISLWLAWYQQKPGKAPKL...,3.672917,1,QVQLQESGPGLVKPSETLSLTCTVSGGSISTYYWSWIRQPAGKGLE...,266,266,1,0
4,CL-222756,EVQLLESGGGLVQPGGSLRLSCAASGFTFGSYAMSWVRQAPGKGLE...,DIQMTQSPSSLSASVGDRVTITCRAGQGISISLAWYQQKPGKVPKL...,1.347917,1,EVQLLESGGGLVQPGGSLRLSCAASGFTFGSYAMSWVRQAPGKGLE...,75,75,1,0
...,...,...,...,...,...,...,...,...,...,...
1496,CL-336571,QVQLVQSGAEVRKPGSSVKVSCKASGGTFSRYSINWVRQAPGQGLE...,QSALTQPRSVSGSPGQSVTISCTGPSSDFGNYNYVSWYQQHPGKAP...,0.674192,0,QVQLVQSGAEVRKPGSSVKVSCKASGGTFSRYSINWVRQAPGQGLE...,-1,1,0,1
1497,CL-336554,EVQLLESGGGLVQPGGSLRLSCAASGFTFSSYAMTWVRQAPGKGLE...,QSVLTQPPSVSGAPGQRVTVSCTGSSSNIGAGFDVHWYQQLSGTAP...,0.677382,0,EVQLLESGGGLVQPGGSLRLSCAASGFTFSSYAMTWVRQAPGKGLE...,-1,25,0,1
1498,CL-336616,EVQLVQSGAEVKKPGASVKVSCKASGYPFTSHGISWVRQAPGQGLE...,ESALTQPASVSGSPGQSITISCTGTTSDIGAYNYVSWYQQHPGKAP...,0.014250,0,EVQLVQSGAEVKKPGASVKVSCKASGYPFTSHGISWVRQAPGQGLE...,-1,1,0,1
1499,CL-336528,QVHLVESGGGVVQPGKSLRLSCAASGFTFSSYGMHWVRQAPGKGLE...,HSALTQPASVSGSPGQSITISCTGTTSDVGSYRLVSWYQQHPGKAP...,0.132031,0,QVHLVESGGGVVQPGKSLRLSCAASGFTFSSYGMHWVRQAPGKGLE...,-1,93,0,1
1500,CL-336805,QVQLQESGPGLVKPSGTLSLTCAVSGGSISSSNWWSWVRQPPGKGL...,DIQMTQSPSSLSASVGDRVTITCQASQDISNYLNWYQQKPGKAPKL...,0.945573,0,QVQLQESGPGLVKPSGTLSLTCAVSGGSISSSNWWSWVRQPPGKGL...,-1,41,0,1

In [ ]:
# % positive
print(f"total dataset: {100*processed_df['Signal Normalised to -ve Control_binarized'].sum()/len(processed_df)}")
print(f"train: {100*train_test_df[train_test_df['Train']==1]['Signal Normalised to -ve Control_binarized'].sum()/len(train_test_df[train_test_df['Train']==1])}")
print(f"test: {100*train_test_df[train_test_df['Test']==1]['Signal Normalised to -ve Control_binarized'].sum()/len(train_test_df[train_test_df['Test']==1])}")

total dataset: 40.37308461025982
train: 40.349417637271216
test: 40.468227424749166

In [3]:
# Read encoding for heavy chain

with open('./../datasets/csi_bli/csi_bli/struc_seqs/struc_seq_heavy_train.json', 'r') as f:
    struc_seq_heavy_train = json.load(f)
    struc_seq_heavy_train_df = pd.DataFrame(
        {'VH': [''.join([aa for aa in seq if aa.isupper()]) for seq in struc_seq_heavy_train],
        'VH_encoding': struc_seq_heavy_train}
        )

with open('./../datasets/csi_bli/csi_bli/struc_seqs/struc_seq_heavy_test.json', 'r') as f:
    struc_seq_heavy_test = json.load(f)
    struc_seq_heavy_test_df = pd.DataFrame(
        {'VH': [''.join([aa for aa in seq if aa.isupper()]) for seq in struc_seq_heavy_test],
        'VH_encoding': struc_seq_heavy_test}
    )

struc_seq_heavy_df = pd.concat([struc_seq_heavy_train_df, struc_seq_heavy_test_df])
train_test_df.merge(struc_seq_heavy_df, on='VH')

,Name,VH,VL,Signal Normalised to -ve Control,Signal Normalised to -ve Control_binarized,VH-VL,Clusters,Clusters_remapping,Train,Test,VH_encoding
0,CL-222760,QVQLQESGPGLVKPSETLSLTCTVSGGSISCGGCYWTWIRQHPGKG...,DIQMTQSPSTLSASVGDRVTITCRASQSISSWLAWYQQKPGKAPKL...,1.327083,1,QVQLQESGPGLVKPSETLSLTCTVSGGSISCGGCYWTWIRQHPGKG...,538,538,1,0,QdVkQaLkQaEkSdGfPdGqLeVdKePaSqEaTkLgSkLmTkCiTa...
1,CL-222759,QVQLQESGPGLVKPSETLSLTCAVSGASISLYYWSWIRQPAGKGLE...,DIQMTQSPSSVSASVGDRVAITCRASQGISSWLAWYQQKPGKAPKL...,2.158333,1,QVQLQESGPGLVKPSETLSLTCAVSGASISLYYWSWIRQPAGKGLE...,486,486,1,0,QdVkQaLkQdEkSdGfPdGqLeVdKePaSqEaTkLgSkLmTkCmAa...
2,CL-222758,LVQLQESGPGLVKPSETLSLTCTVSGGSISSYYWSWIRQPAGKGLE...,DIQMTQSPSTLSASVGDRVTITCRASQSISSWLAWYQQKPGKAPKL...,1.029167,1,LVQLQESGPGLVKPSETLSLTCTVSGGSISSYYWSWIRQPAGKGLE...,71,71,1,0,LdVkQaLkQdEkSdGaPdGqLeVdKePaSqEaTkLgSkLiTkCmTa...
3,CL-222758,LVQLQESGPGLVKPSETLSLTCTVSGGSISSYYWSWIRQPAGKGLE...,DIQMTQSPSTLSASVGDRVTITCRASQSISSWLAWYQQKPGKAPKL...,1.029167,1,LVQLQESGPGLVKPSETLSLTCTVSGGSISSYYWSWIRQPAGKGLE...,71,71,1,0,LdVkQaLkQdEkSdGfPdGqLeVdKePaSqEaTkLgSkLiTkCmTa...
4,CL-222757,QVQLQESGPGLVKPSETLSLTCTVSGGSISTYYWSWIRQPAGKGLE...,DIQMTQSPSSVSASVGDRVTITCRASQGISLWLAWYQQKPGKAPKL...,3.672917,1,QVQLQESGPGLVKPSETLSLTCTVSGGSISTYYWSWIRQPAGKGLE...,266,266,1,0,QdVkQaLkQaEkSdGfPdGqLeVdKePaSqEaTkLgSkLiTkCmTa...
...,...,...,...,...,...,...,...,...,...,...,...
3632,CL-336571,QVQLVQSGAEVRKPGSSVKVSCKASGGTFSRYSINWVRQAPGQGLE...,QSALTQPRSVSGSPGQSVTISCTGPSSDFGNYNYVSWYQQHPGKAP...,0.674192,0,QVQLVQSGAEVRKPGSSVKVSCKASGGTFSRYSINWVRQAPGQGLE...,-1,1,0,1,QdVkQaLkVaQkSdGaAaEeVeReKePaGqSaSkVdKkViSkCiKa...
3633,CL-336554,EVQLLESGGGLVQPGGSLRLSCAASGFTFSSYAMTWVRQAPGKGLE...,QSVLTQPPSVSGAPGQRVTVSCTGSSSNIGAGFDVHWYQQLSGTAP...,0.677382,0,EVQLLESGGGLVQPGGSLRLSCAASGFTFSSYAMTWVRQAPGKGLE...,-1,25,0,1,EdVkQaLkLaEkSdGfGaGdLeVdQePaGqGaSkLtRkLiSkCiAa...
3634,CL-336616,EVQLVQSGAEVKKPGASVKVSCKASGYPFTSHGISWVRQAPGQGLE...,ESALTQPASVSGSPGQSITISCTGTTSDIGAYNYVSWYQQHPGKAP...,0.014250,0,EVQLVQSGAEVKKPGASVKVSCKASGYPFTSHGISWVRQAPGQGLE...,-1,1,0,1,EdVwQaLkVaQkSdGaAaEeVeKaKePaGqAaSkVdKkViSkCiKa...
3635,CL-336528,QVHLVESGGGVVQPGKSLRLSCAASGFTFSSYGMHWVRQAPGKGLE...,HSALTQPASVSGSPGQSITISCTGTTSDVGSYRLVSWYQQHPGKAP...,0.132031,0,QVHLVESGGGVVQPGKSLRLSCAASGFTFSSYGMHWVRQAPGKGLE...,-1,93,0,1,QdVkHaLkVaEkSdGfGaGdVeVdQePaGqKaSkLtRkLmSkCiAa...
3636,CL-336805,QVQLQESGPGLVKPSGTLSLTCAVSGGSISSSNWWSWVRQPPGKGL...,DIQMTQSPSSLSASVGDRVTITCQASQDISNYLNWYQQKPGKAPKL...,0.945573,0,QVQLQESGPGLVKPSGTLSLTCAVSGGSISSSNWWSWVRQPPGKGL...,-1,41,0,1,QdVkQaLkQaEkSdGfPdGqLeVdKePaSqGaTkLgSkLmTkCiAa...

In [31]:
## VH sequence with most number of encodings
unique_encodings = struc_seq_heavy_df[struc_seq_heavy_df['VH']==struc_seq_heavy_df['VH'].value_counts().index[0]].drop_duplicates('VH_encoding')['VH_encoding'].to_list()

[[idx,(aa1, aa2)] for idx,(aa1, aa2) in enumerate(zip(unique_encodings[0],unique_encodings[3])) if aa1!=aa2]

[[57, ('q', 'l')],
 [103, ('g', 'd')],
 [107, ('p', 'v')],
 [153, ('r', 'n')],
 [169, ('n', 'r')],
 [191, ('i', 'm')],
 [197, ('d', 'a')]]

In [32]:
unique_encodings[0][40:62],unique_encodings[3][40:62]

('SkCiAaAtSdGpFdTqFqSlTq', 'SkCiAaAtSdGpFdTqFlSlTq')

In [68]:
# Read encoding for heavy chain
with open('./../datasets/csi_bli/csi_bli/struc_seqs/struc_seq_heavy_train.json', 'r') as f:
    struc_seq_vh_train = json.load(f)
    struc_seq_vh_train_df = pd.DataFrame(
        {'VH': [''.join([aa for aa in seq if aa.isupper()]) for seq in struc_seq_vh_train],
        'VH_encoding': struc_seq_vh_train}
    )

with open('./../datasets/csi_bli/csi_bli/struc_seqs/struc_seq_heavy_test.json', 'r') as f:
    struc_seq_vh_test = json.load(f)
    struc_seq_vh_test_df = pd.DataFrame(
        {'VH': [''.join([aa for aa in seq if aa.isupper()]) for seq in struc_seq_vh_test],
        'VH_encoding': struc_seq_vh_test}
    )

struc_seq_vh_df = pd.concat([struc_seq_vh_train_df, struc_seq_vh_test_df])

# Read encoding for light chain
with open('./../datasets/csi_bli/csi_bli/struc_seqs/struc_seq_light_train.json', 'r') as f:
    struc_seq_vl_train = json.load(f)
    struc_seq_vl_train_df = pd.DataFrame(
        {'VL': [''.join([aa for aa in seq if aa.isupper()]) for seq in struc_seq_vl_train],
        'VL_encoding': struc_seq_vl_train}
    )

with open('./../datasets/csi_bli/csi_bli/struc_seqs/struc_seq_light_test.json', 'r') as f:
    struc_seq_vl_test = json.load(f)
    struc_seq_vl_test_df = pd.DataFrame(
        {'VL': [''.join([aa for aa in seq if aa.isupper()]) for seq in struc_seq_vl_test],
        'VL_encoding': struc_seq_vl_test}
    )

struc_seq_vl_df = pd.concat([struc_seq_vl_train_df, struc_seq_vl_test_df])

# Combined VH-VL
struc_seq_vh_vl_train_df = pd.DataFrame(
    {'VH-VL': [vh+'-'+vl for vh,vl in zip(struc_seq_vh_train_df['VH'].to_list(), struc_seq_vl_train_df['VL'].to_list())],
    'VH-VL_encoding': [vh+'##'+vl for vh,vl in zip(struc_seq_vh_train_df['VH_encoding'].to_list(), struc_seq_vl_train_df['VL_encoding'].to_list())]}
)

struc_seq_vh_vl_test_df = pd.DataFrame(
    {'VH-VL': [vh+'-'+vl for vh,vl in zip(struc_seq_vh_test_df['VH'].to_list(), struc_seq_vl_test_df['VL'].to_list())],
    'VH-VL_encoding': [vh+'##'+vl for vh,vl in zip(struc_seq_vh_test_df['VH_encoding'].to_list(), struc_seq_vl_test_df['VL_encoding'].to_list())]}
)

struc_seq_vh_vl_df = pd.concat([struc_seq_vh_vl_train_df, struc_seq_vh_vl_test_df])

In [69]:
# Unique sequences
print(f"The number of unique VH sequences in train test: {len(train_test_df['VH'].unique())}")
print(f"The number of unique VL sequences in train test: {len(train_test_df['VL'].unique())}")
print(f"The number of unique VH-VL sequences in train test: {len(train_test_df['VH-VL'].unique())}")

# struc_seq_vh_df
print(f"The number of unique VH sequences in train test: {len(struc_seq_vh_df['VH'].unique())}")
print(f"The number of unique VH encoding sequences in train test: {len(struc_seq_vh_df['VH_encoding'].unique())}")

# struc_seq_vl_df
print(f"The number of unique VL sequences in train test: {len(struc_seq_vl_df['VL'].unique())}")
print(f"The number of unique VL encoding sequences in train test: {len(struc_seq_vl_df['VL_encoding'].unique())}")

# struc_seq_vh_vl_df
print(f"The number of unique VH-VL sequences in train test: {len(struc_seq_vh_vl_df['VH-VL'].unique())}")
print(f"The number of unique VH-VL encoding sequences in train test: {len(struc_seq_vh_vl_df['VH-VL_encoding'].unique())}")

The number of unique VH sequences in train test: 1257
The number of unique VL sequences in train test: 1019
The number of unique VH-VL sequences in train test: 1501
The number of unique VH sequences in train test: 1257
The number of unique VH encoding sequences in train test: 1499
The number of unique VL sequences in train test: 1019
The number of unique VL encoding sequences in train test: 1475
The number of unique VH-VL sequences in train test: 1501
The number of unique VH-VL encoding sequences in train test: 1501

In [124]:
train_test_df.merge(struc_seq_vh_df, on='VH')[['Train', 
                                               'Test', 
                                               'VH_encoding',
                                               'Signal Normalised to -ve Control_binarized']].drop_duplicates('VH_encoding')

,Train,Test,VH_encoding,Signal Normalised to -ve Control_binarized
0,1,0,QdVkQaLkQaEkSdGfPdGqLeVdKePaSqEaTkLgSkLmTkCiTa...,1
1,1,0,QdVkQaLkQdEkSdGfPdGqLeVdKePaSqEaTkLgSkLmTkCmAa...,1
2,1,0,LdVkQaLkQdEkSdGaPdGqLeVdKePaSqEaTkLgSkLiTkCmTa...,1
3,1,0,LdVkQaLkQdEkSdGfPdGqLeVdKePaSqEaTkLgSkLiTkCmTa...,1
4,1,0,QdVkQaLkQaEkSdGfPdGqLeVdKePaSqEaTkLgSkLiTkCmTa...,1
...,...,...,...,...
3632,0,1,QdVkQaLkVaQkSdGaAaEeVeReKePaGqSaSkVdKkViSkCiKa...,0
3633,0,1,EdVkQaLkLaEkSdGfGaGdLeVdQePaGqGaSkLtRkLiSkCiAa...,0
3634,0,1,EdVwQaLkVaQkSdGaAaEeVeKaKePaGqAaSkVdKkViSkCiKa...,0
3635,0,1,QdVkHaLkVaEkSdGfGaGdVeVdQePaGqKaSkLtRkLmSkCiAa...,0
3636,0,1,QdVkQaLkQaEkSdGfPdGqLeVdKePaSqGaTkLgSkLmTkCiAa...,0

In [ ]:
np.sum([1 if vh==vh_ else 0 for vh, vh_ in zip(train_test_df['VH-VL'].to_list(), struc_seq_vh_vl_df['VH-VL'].to_list())])